### ISSUE TITLE
Cannot see anything on arunos when type "help" or any other linux command

### ISSUE THREAD

**Issue by endinferno** [pykello/arunos#3]
I'm trying to learn how to write an OS on ARM recently. I had some problems when running your project.
I cannot see anything when I type "help" on the shell.
[help_no_print](http://121.5.185.52/pic/github_issue_pic/help-no-print.png)
My environment is Linux version 4.15.0-117-generic, ubuntu 18.04.

**Comment by ghost** [comment]
This shell is not support linux commands!
To example **Hello, world!** input `1` and press **_`enter↵`_**

**Comment by MathewRo** [comment]
Could you help with the documentation for all console commands?

**Comment by ghost** [comment]
@MathewRo Yes, I can help you!

**Comment by endinferno** [comment]
@Vector1dev Hope to get your documentation soon! i'll just close this issue.
